/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterTokenRouteImport } from './routes/register.$token'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ApiScenarioSessionIdRouteImport } from './routes/api/scenario.$sessionId'
import { Route as AuthenticatedTrainingSlugRouteImport } from './routes/_authenticated/training.$slug'
import { Route as AuthenticatedResultsSessionIdRouteImport } from './routes/_authenticated/results.$sessionId'
import { Route as AuthenticatedPlaySessionIdRouteImport } from './routes/_authenticated/play.$sessionId'
import { Route as AuthenticatedAdminScenariosRouteImport } from './routes/_authenticated/admin.scenarios'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as AuthenticatedAdminRegistrationsRouteImport } from './routes/_authenticated/admin.registrations'
import { Route as AuthenticatedAdminEmployeesRouteImport } from './routes/_authenticated/admin.employees'
import { Route as AuthenticatedAdminCampaignsRouteImport } from './routes/_authenticated/admin.campaigns'
import { Route as AuthenticatedAdminAdministratorsRouteImport } from './routes/_authenticated/admin.administrators'
import { Route as AuthenticatedTrainingSlugStartRouteImport } from './routes/_authenticated/training.$slug.start'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterTokenRoute = RegisterTokenRouteImport.update({
  id: '/register/$token',
  path: '/register/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiScenarioSessionIdRoute = ApiScenarioSessionIdRouteImport.update({
  id: '/api/scenario/$sessionId',
  path: '/api/scenario/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTrainingSlugRoute =
  AuthenticatedTrainingSlugRouteImport.update({
    id: '/training/$slug',
    path: '/training/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResultsSessionIdRoute =
  AuthenticatedResultsSessionIdRouteImport.update({
    id: '/results/$sessionId',
    path: '/results/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlaySessionIdRoute =
  AuthenticatedPlaySessionIdRouteImport.update({
    id: '/play/$sessionId',
    path: '/play/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminScenariosRoute =
  AuthenticatedAdminScenariosRouteImport.update({
    id: '/scenarios',
    path: '/scenarios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRegistrationsRoute =
  AuthenticatedAdminRegistrationsRouteImport.update({
    id: '/registrations',
    path: '/registrations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEmployeesRoute =
  AuthenticatedAdminEmployeesRouteImport.update({
    id: '/employees',
    path: '/employees',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCampaignsRoute =
  AuthenticatedAdminCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdministratorsRoute =
  AuthenticatedAdminAdministratorsRouteImport.update({
    id: '/administrators',
    path: '/administrators',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedTrainingSlugStartRoute =
  AuthenticatedTrainingSlugStartRouteImport.update({
    id: '/start',
    path: '/start',
    getParentRoute: () => AuthenticatedTrainingSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/register/$token': typeof RegisterTokenRoute
  '/admin/administrators': typeof AuthenticatedAdminAdministratorsRoute
  '/admin/campaigns': typeof AuthenticatedAdminCampaignsRoute
  '/admin/employees': typeof AuthenticatedAdminEmployeesRoute
  '/admin/registrations': typeof AuthenticatedAdminRegistrationsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/scenarios': typeof AuthenticatedAdminScenariosRoute
  '/play/$sessionId': typeof AuthenticatedPlaySessionIdRoute
  '/results/$sessionId': typeof AuthenticatedResultsSessionIdRoute
  '/training/$slug': typeof AuthenticatedTrainingSlugRouteWithChildren
  '/api/scenario/$sessionId': typeof ApiScenarioSessionIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/training/$slug/start': typeof AuthenticatedTrainingSlugStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/register/$token': typeof RegisterTokenRoute
  '/admin/administrators': typeof AuthenticatedAdminAdministratorsRoute
  '/admin/campaigns': typeof AuthenticatedAdminCampaignsRoute
  '/admin/employees': typeof AuthenticatedAdminEmployeesRoute
  '/admin/registrations': typeof AuthenticatedAdminRegistrationsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/scenarios': typeof AuthenticatedAdminScenariosRoute
  '/play/$sessionId': typeof AuthenticatedPlaySessionIdRoute
  '/results/$sessionId': typeof AuthenticatedResultsSessionIdRoute
  '/training/$slug': typeof AuthenticatedTrainingSlugRouteWithChildren
  '/api/scenario/$sessionId': typeof ApiScenarioSessionIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/training/$slug/start': typeof AuthenticatedTrainingSlugStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/register/$token': typeof RegisterTokenRoute
  '/_authenticated/admin/administrators': typeof AuthenticatedAdminAdministratorsRoute
  '/_authenticated/admin/campaigns': typeof AuthenticatedAdminCampaignsRoute
  '/_authenticated/admin/employees': typeof AuthenticatedAdminEmployeesRoute
  '/_authenticated/admin/registrations': typeof AuthenticatedAdminRegistrationsRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/scenarios': typeof AuthenticatedAdminScenariosRoute
  '/_authenticated/play/$sessionId': typeof AuthenticatedPlaySessionIdRoute
  '/_authenticated/results/$sessionId': typeof AuthenticatedResultsSessionIdRoute
  '/_authenticated/training/$slug': typeof AuthenticatedTrainingSlugRouteWithChildren
  '/api/scenario/$sessionId': typeof ApiScenarioSessionIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/training/$slug/start': typeof AuthenticatedTrainingSlugStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/dashboard'
    | '/leaderboard'
    | '/register/$token'
    | '/admin/administrators'
    | '/admin/campaigns'
    | '/admin/employees'
    | '/admin/registrations'
    | '/admin/reports'
    | '/admin/scenarios'
    | '/play/$sessionId'
    | '/results/$sessionId'
    | '/training/$slug'
    | '/api/scenario/$sessionId'
    | '/admin/'
    | '/training/$slug/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/leaderboard'
    | '/register/$token'
    | '/admin/administrators'
    | '/admin/campaigns'
    | '/admin/employees'
    | '/admin/registrations'
    | '/admin/reports'
    | '/admin/scenarios'
    | '/play/$sessionId'
    | '/results/$sessionId'
    | '/training/$slug'
    | '/api/scenario/$sessionId'
    | '/admin'
    | '/training/$slug/start'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/leaderboard'
    | '/register/$token'
    | '/_authenticated/admin/administrators'
    | '/_authenticated/admin/campaigns'
    | '/_authenticated/admin/employees'
    | '/_authenticated/admin/registrations'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/scenarios'
    | '/_authenticated/play/$sessionId'
    | '/_authenticated/results/$sessionId'
    | '/_authenticated/training/$slug'
    | '/api/scenario/$sessionId'
    | '/_authenticated/admin/'
    | '/_authenticated/training/$slug/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  RegisterTokenRoute: typeof RegisterTokenRoute
  ApiScenarioSessionIdRoute: typeof ApiScenarioSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/$token': {
      id: '/register/$token'
      path: '/register/$token'
      fullPath: '/register/$token'
      preLoaderRoute: typeof RegisterTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/scenario/$sessionId': {
      id: '/api/scenario/$sessionId'
      path: '/api/scenario/$sessionId'
      fullPath: '/api/scenario/$sessionId'
      preLoaderRoute: typeof ApiScenarioSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/training/$slug': {
      id: '/_authenticated/training/$slug'
      path: '/training/$slug'
      fullPath: '/training/$slug'
      preLoaderRoute: typeof AuthenticatedTrainingSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/results/$sessionId': {
      id: '/_authenticated/results/$sessionId'
      path: '/results/$sessionId'
      fullPath: '/results/$sessionId'
      preLoaderRoute: typeof AuthenticatedResultsSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/play/$sessionId': {
      id: '/_authenticated/play/$sessionId'
      path: '/play/$sessionId'
      fullPath: '/play/$sessionId'
      preLoaderRoute: typeof AuthenticatedPlaySessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/scenarios': {
      id: '/_authenticated/admin/scenarios'
      path: '/scenarios'
      fullPath: '/admin/scenarios'
      preLoaderRoute: typeof AuthenticatedAdminScenariosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/registrations': {
      id: '/_authenticated/admin/registrations'
      path: '/registrations'
      fullPath: '/admin/registrations'
      preLoaderRoute: typeof AuthenticatedAdminRegistrationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/employees': {
      id: '/_authenticated/admin/employees'
      path: '/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AuthenticatedAdminEmployeesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/campaigns': {
      id: '/_authenticated/admin/campaigns'
      path: '/campaigns'
      fullPath: '/admin/campaigns'
      preLoaderRoute: typeof AuthenticatedAdminCampaignsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/administrators': {
      id: '/_authenticated/admin/administrators'
      path: '/administrators'
      fullPath: '/admin/administrators'
      preLoaderRoute: typeof AuthenticatedAdminAdministratorsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/training/$slug/start': {
      id: '/_authenticated/training/$slug/start'
      path: '/start'
      fullPath: '/training/$slug/start'
      preLoaderRoute: typeof AuthenticatedTrainingSlugStartRouteImport
      parentRoute: typeof AuthenticatedTrainingSlugRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAdministratorsRoute: typeof AuthenticatedAdminAdministratorsRoute
  AuthenticatedAdminCampaignsRoute: typeof AuthenticatedAdminCampaignsRoute
  AuthenticatedAdminEmployeesRoute: typeof AuthenticatedAdminEmployeesRoute
  AuthenticatedAdminRegistrationsRoute: typeof AuthenticatedAdminRegistrationsRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminScenariosRoute: typeof AuthenticatedAdminScenariosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAdministratorsRoute: AuthenticatedAdminAdministratorsRoute,
  AuthenticatedAdminCampaignsRoute: AuthenticatedAdminCampaignsRoute,
  AuthenticatedAdminEmployeesRoute: AuthenticatedAdminEmployeesRoute,
  AuthenticatedAdminRegistrationsRoute: AuthenticatedAdminRegistrationsRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminScenariosRoute: AuthenticatedAdminScenariosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedTrainingSlugRouteChildren {
  AuthenticatedTrainingSlugStartRoute: typeof AuthenticatedTrainingSlugStartRoute
}

const AuthenticatedTrainingSlugRouteChildren: AuthenticatedTrainingSlugRouteChildren =
  {
    AuthenticatedTrainingSlugStartRoute: AuthenticatedTrainingSlugStartRoute,
  }

const AuthenticatedTrainingSlugRouteWithChildren =
  AuthenticatedTrainingSlugRoute._addFileChildren(
    AuthenticatedTrainingSlugRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedPlaySessionIdRoute: typeof AuthenticatedPlaySessionIdRoute
  AuthenticatedResultsSessionIdRoute: typeof AuthenticatedResultsSessionIdRoute
  AuthenticatedTrainingSlugRoute: typeof AuthenticatedTrainingSlugRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedPlaySessionIdRoute: AuthenticatedPlaySessionIdRoute,
  AuthenticatedResultsSessionIdRoute: AuthenticatedResultsSessionIdRoute,
  AuthenticatedTrainingSlugRoute: AuthenticatedTrainingSlugRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  RegisterTokenRoute: RegisterTokenRoute,
  ApiScenarioSessionIdRoute: ApiScenarioSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
